"""finished_schema_linkage

Revision ID: 156bf13101ba
Revises: af8a061a64c1
Create Date: 2025-11-28 20:01:51.658820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156bf13101ba'
down_revision: Union[str, Sequence[str], None] = 'af8a061a64c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('sensor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'sensors', ['sensor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'sensor_id')
    op.drop_column('notifications', 'location_id')
    # ### end Alembic commands ###
